name: Check formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: mobile

jobs:
  mobile-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting
      run: yarn run checkFormatting
  api-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting
      run: yarn run checkFormatting
