name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  test-mobile:
    defaults:
      run:
        working-directory: mobile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
  test-api:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
