name: Run mobile tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
defaults:
  run:
    working-directory: mobile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
